function act08_export_table_tex(T, outFile, captionText, labelText)
%ACT08_EXPORT_TABLE_TEX Exports a compact booktabs table for LaTeX.

folderPath = fileparts(outFile);
if ~isfolder(folderPath)
    mkdir(folderPath);
end

fid = fopen(outFile, 'w');
if fid < 0
    error('Cannot write %s', outFile);
end
cleanup = onCleanup(@() fclose(fid));

align = ['l', repmat('r', 1, width(T) - 1)];
fprintf(fid, '%% Auto-generated by src/matlab/main_act08_grupo1.m\n');
fprintf(fid, '\\begin{table}[H]\n');
fprintf(fid, '\\centering\n');
fprintf(fid, '\\caption{%s}\n', captionText);
fprintf(fid, '\\label{%s}\n', labelText);
fprintf(fid, '\\small\n');
fprintf(fid, '\\begin{tabular}{@{}%s@{}}\n', align);
fprintf(fid, '\\toprule\n');

headers = T.Properties.VariableNames;
for c = 1:numel(headers)
    if c > 1
        fprintf(fid, ' & ');
    end
    fprintf(fid, '%s', tex_escape(headers{c}));
end
fprintf(fid, ' \\\\\n\\midrule\n');

for r = 1:height(T)
    for c = 1:width(T)
        if c > 1
            fprintf(fid, ' & ');
        end
        value = T{r, c};
        if iscell(value)
            value = value{1};
        end
        if ischar(value) || isstring(value)
            fprintf(fid, '%s', tex_escape(char(value)));
        elseif isnumeric(value)
            fprintf(fid, '%.3g', value);
        else
            fprintf(fid, '%s', tex_escape(char(string(value))));
        end
    end
    fprintf(fid, ' \\\\\n');
end

fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fprintf(fid, '\\end{table}\n');
end

function s = tex_escape(s)
s = strrep(s, '\', '\textbackslash{}');
s = strrep(s, '_', '\_');
s = strrep(s, '%', '\%');
s = strrep(s, '&', '\&');
s = strrep(s, '#', '\#');
end
